config/routes.rb
 Rails.application.routes.draw do

  root 'welcome#index'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-out', to: 'authentication#destroy'
  get 'sign-in', to: 'authentication#new', as: "signin"
  post 'sign-in', to: 'authentication#create'


  get 'terms' => 'terms#index'
  get 'about' => 'about#index'
  get '/faq'  => 'common_questions#index'

  get 'stories' => 'pivotaltracker#show'
  
  resources :users

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :tasks, only: [] do
    resources :comments, only: [:create]
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base

  ROLE_MEMBER = 'Member'
  ROLE_OWNER = 'Owner'
  ROLE = [ROLE_MEMBER, ROLE_OWNER]


  belongs_to :project
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :project_id, message: "has already been added to this project"
  validates :user_id, presence: true
  validates :role, presence: true


end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action do
    @project = Project.find(params[:project_id])
  end
  before_action :member_or_admin_auth, except: [:destroy]
  before_action :set_membership, only: [:update, :destroy]
  before_action :ensure_user_is_not_the_last_owner, only: [:update, :destroy]
  before_action :find_member, only: [:update, :destroy]
  before_action :find_user_for_now
  before_action :verify_owner_access, only: [:update, :destroy]


  def index
    @membership = @project.memberships.new
  end

  def create
    @membership = @project.memberships.new(membership_params)
    if @membership.save
      flash[:success] = "#{@membership.user.full_name} was successfully added"
      redirect_to project_memberships_path
    else
      render :index
    end
  end

  def update
    if @membership.update(membership_params)
      flash[:success] = "#{@membership.user.full_name} was successfully updated"
      redirect_to project_memberships_path
    end
  end

  def destroy
    @membership.destroy
    if current_user.id == @membership.user_id
     flash[:success] = "#{@membership.user.full_name} was successfully removed"
     redirect_to projects_path
   else
     flash[:success] = "#{@membership.user.full_name} was successfully removed"
    redirect_to project_memberships_path
   end
  end

  private

    def membership_params
      params.require(:membership).permit(:role, :project_id, :user_id)
    end

    def find_member
      @current_member = current_user.memberships.find_by(project_id: @project.id)
      unless @current_member.role == "Owner" || @project.memberships.pluck(:user_id).include?(current_user.id)
        flash[:danger] = "You do not have access"
        redirect_to project_path(@project)
      end
    end

   def cannot_delete_without_permissions
     unless @project.memberships.where(user_id: current_user.id) || current_user.admin
       flash[:danger] = 'You do not have access'
       redirect_to projects_path
     end
   end


   def find_user_for_now
     @current_member = current_user.memberships.find_by(project_id: @project.id)
   end

   def set_membership
     @membership = @project.memberships.find(params[:id])
   end

  def ensure_user_is_not_the_last_owner
    if current_user.is_project_owner(@project) && @project.memberships.where(role: 'Owner').count <= 1 && @membership.role == 'Owner'
      flash[:danger] = 'Projects must have at least one owner'
      redirect_to project_memberships_path(@project)
    end
  end

  def verify_owner_access
    unless @project.memberships.find_by(user_id: current_user.id).role == "Owner" || @project.memberships.find(params[:id]).user.id == current_user.id
      if @project.memberships.pluck(:user_id).include?(current_user.id)
        flash[:danger] = 'You do not have access'
        redirect_to projects_path
      end
    end
  end

  def member_or_admin_auth
     unless (current_user.is_project_member(@project) || current_user.admin)
       flash[:danger] = 'You do not have access to that project'
       redirect_to projects_path
     end
   end
end

app/views/memberships/index.html.erb
<div class="container">

<div class="page-header">
  <h1>
    <%= @project.name %>: Manage Members
  </h1>
</div>

<ol class="breadcrumb">
  <li><%= link_to 'Projects', projects_path(@projects) %></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li class="active">Memberships</li>
</ol>

<div class="row">
  <% if @membership.errors.any? %>
    <div class="form-group">
      <div class="col-md-7">
        <div class="alert alert-danger">
          <h3><%= pluralize(@membership.errors.count, "error") %> prohibited this form from being saved </h3>
          <ul>
            <% @membership.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% if (@current_member.present? && @current_member.role == 'Owner') || current_user.admin %>
  <div class="row">
    <%= form_for [@project, @membership], html: {class: "form-inline" } do |f| %>
      <div class='col-md-7'>
        <div class = 'well'>
          <%= f.collection_select(:user_id, User.all, :id, :full_name, {prompt: "Please select a user..."},{class: 'form-control'}) %>
          <%= f.collection_select(:role, Membership::ROLE, :to_s, :to_s, {},{class: 'form-control'}) %>
          <%= f.submit "Add New Member", class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div class="row">
  <div class="col-md-8">
    <table class="table">
      <tbody>
        <% @project.memberships.each do |membership| %>
          <% if membership.id %>
            <tr>
            <td> <%= link_to "#{membership.user.full_name}", user_path(membership.user.id) %></td>
            <% if current_user.is_project_owner(@project) || current_user.admin %>
              <%= form_for [@project, membership], htm: {class: "form-inline"} do |f| %>
                <td> <%= f.collection_select(:role, Membership::ROLE, :to_s, :to_s, {}, {class: 'form-control'}) %></td>
                <td> <%= f.submit "Update", class: 'btn btn-primary' %> </td>
                <% if  @project.memberships.where(role: 'Owner').count == 1 && membership.role == 'Owner' %>
                  <td>You are the Last Owner</td>
                <% end %>
              <% end %>
            <% else %>
              <td> <%= membership.role.downcase %> </td>
            <% end %>
            <td>
              <% if membership.user_id == current_user.id || current_user.is_project_owner(@project) || current_user.admin %>
                <% unless @project.memberships.where(role: 'Owner').count == 1 && membership.role == 'Owner' %>
                  <%= link_to '', project_membership_path(@project, membership), method: :delete, class: "glyphicon glyphicon-remove" %>
                <% end %>
              <% end %>
            </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>