config/routes.rb
 Rails.application.routes.draw do

  root 'welcome#index'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-out', to: 'authentication#destroy'
  get 'sign-in', to: 'authentication#new', as: "signin"
  post 'sign-in', to: 'authentication#create'


  get 'terms' => 'terms#index'
  get 'about' => 'about#index'
  get '/faq'  => 'common_questions#index'

  get 'stories' => 'pivotaltracker#show'
  
  resources :users

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :tasks, only: [] do
    resources :comments, only: [:create]
  end
end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :description, presence: true
  belongs_to :project


  has_many :comments, dependent: :destroy

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  before_action do
    @project = Project.find(params[:project_id])
  end

  before_action :authenticate_user
  before_action :project_member_permission

  def index
    @tasks = @project.tasks
  end

  def new
  @task = Task.new
  end


  def show
    @task = Task.find(params[:id])
    @comment = Comment.new
    @comments = @task.comments
  end

  def edit
     @task = Task.find(params[:id])
  end


  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      flash[:success] = "Task was successfully created!"
       redirect_to project_task_path(@project, @task)
    else
      render :new
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success] = "Task was successfully updated!"
      redirect_to project_task_path
    else
      render :edit
    end
  end


  def destroy
    Task.find(params[:id]).destroy
    flash[:success] = "Task was successfully deleted."
    redirect_to project_tasks_path(@project)
  end

  def project_member_permission
    project = Project.find(params[:project_id])
    unless current_user.admin || current_user.is_project_member(project)
      flash[:danger] = "You do not have access to that project"
      redirect_to projects_path
    end
  end


  private

  def task_params
    params.require(:task).permit(:description, :complete, :due_date)
  end

end

app/views/tasks/_form.html.erb
<div class="container">
<%= form_for([@project, @task], html: {class: 'form-horizontal'}) do |f| %>

 <%= render partial: "shared/errors", locals: { object: @task } %>


  <div class= 'form-group'>
      <%= f.label :description, class: 'col-sm-2 control-label'%>
    <div class= 'col-sm-4'>
      <%= f.text_field :description, class: 'form-control' %>
    </div>
  </div>

  <div class= 'form-group'>
    <%= f.label :due_date, class: 'col-sm-2 control-label'%>
    <div class= 'col-sm-3'>
      <%= f.date_field :due_date, class: 'form-control' %>
    </div>
  </div>

  <% unless @task.new_record? %>
    <div class= 'form-group'>
      <div class= 'col-sm-offset-2 col-sm-10'>
        <div class= 'checkbox'>
          <label>
            <%= f.check_box :complete %> Complete
          </label>
        </div>
      </div>
    </div>
  <% end %>




  <div class= 'form-group'>
    <div class= 'col-sm-offset-2 col-sm-10'>
      <%= f.submit "#{name_of_button} Task", class: 'btn btn-primary' %>
      <%= link_to "Cancel", project_tasks_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>
</div>

app/views/tasks/edit.html.erb
<div class= 'container'>
  <h1> Edit task </h1>
  <br>
  <ul class='breadcrumb'>
    <li><%= link_to 'Projects', projects_path %></li>
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li><%= link_to 'Tasks', project_tasks_path %></li>
    <li> <%= link_to @task.description, project_task_path %></li>
    <li> Edit </li>
  </ul>

  <p>
    <% if @task.due_date %>
    <strong>Due On:</strong>
      <%= @task.due_date.strftime("%m/%d/%Y") %>
    <% end %>
  </p>

</div>

<%= render partial: "form", locals: { name_of_button: "Update"} %>

app/views/tasks/index.html.erb
<div class = 'container'>

  <div class = 'page-header'>

    <%= link_to 'New Task', new_project_task_path, class: "btn btn-info pull-right" %>
    <h1><%= "Tasks for #{@project.name}" %></h1>
  </div>

  <ol class='breadcrumb'>
    <li> <%= link_to "Projects", projects_path %>
    <li> <%= link_to @project.name, project_path(@project) %></li>
    <li class="active">Tasks</li>
  </ol>


  <table class= "table">
    <thead>
      <tr>
        <div class= "col-sm-3">
        <th>Description</th>
        </div>
        <div class= "col-sm-3">
        <th>Due Date</th>
      </div>
      </tr>
    </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td class= "col-sm-3">
        <% if task.complete %>
          <strike><%= link_to task.description, project_task_path(@project, task) %></strike>
        <% else %>
          <%= link_to task.description, project_task_path(@project,task) %>
          <a><span class="badge"><%= task.comments.count %></span></a>
        <% end %>
      </td>

      <td class= "col-sm-3">
          <% if task.due_date %>
          <%= task.due_date.strftime("%m/%d/%Y") %>
          <% end %>
      </td>

      <td>
        <div class="pull-right">
          <%= link_to 'Edit', edit_project_task_path(@project, task), class: "btn btn-info" %>
          <%= link_to '', project_task_path(@project, task), method: :delete, class: "glyphicon glyphicon-remove" %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/tasks/new.html.erb
<div class = 'container'>
<h1>New Task</h1>

<hr>

    <ul class='breadcrumb'>
      <li><%= link_to 'Projects', projects_path %></li>
      <li><%= link_to @project.name, project_path(@project) %></li>
      <li><%= link_to 'Tasks', project_tasks_path %></li>
      <li class="active">New</li>
    </ul>
</div>

<br>
<%= render partial: "form", locals: { name_of_button: "Create"} %>

app/views/tasks/show.html.erb
  <div class= 'container'>
    <div class= 'page-header'>
      <h1><% if @task.complete == true %>
        <s><%= @task.description %></s>
      <% else %>
        <%= @task.description %>
      <% end %>
      <div class="pull-right">
        <%= link_to "Edit", edit_project_task_path(@project, @task), class: "btn btn-info" %>
      </div>
    </h1>
  </div>

  <div>
    <ol class="breadcrumb">
      <li><%=link_to "Projects", projects_path%></li>
      <li><%=link_to "#{@project.name}", project_path(@project)%></li>
      <li><%=link_to "Tasks", project_tasks_path(@project)%></li>
      <li class="active"><%=@task.description%></li>
    </ol>
  </div>

        <p>
          <% if @task.due_date %>
          <strong>Due On:</strong>
            <%= @task.due_date.strftime("%m/%d/%Y") %>
          <% end %>
        </p>

  <head><h3>Comments</h3></head>

      <% @comments.each do |comment| %>
        <p>
        <div class="row">
          <div class="col-md-3">
            <% if comment.user == nil %>
              <%= "(deleted user)" %>
            <% else %>
          <%= link_to "#{comment.user.full_name}", user_path(comment.user) %>
        <% end %>

          <div class= "text-muted">
            <%= "#{time_ago_in_words(comment.created_at)} ago" %>
          </div>

      </div>

      <div class='container'>
        <div class="col-md-9 pull-right">
          <%= comment.text %>
        </div>
      </div>
    </div>
    </p>

      <% end %>




    <%= form_for([@task, @comment]) do |f| %>
    <p>
      <div class="col-md-9 pull-right">
        <%= f.text_area :text, class: "form-control" %><br>
          </p>
            <%= f.submit "Add Comment", class: "btn btn-primary" %>
              </div>

            <% end %>




</div> <!-- container div-->