config/routes.rb
 Rails.application.routes.draw do

  root 'welcome#index'

  get 'sign-up', to: 'registrations#new'
  post 'sign-up', to: 'registrations#create'
  get 'sign-out', to: 'authentication#destroy'
  get 'sign-in', to: 'authentication#new', as: "signin"
  post 'sign-in', to: 'authentication#create'


  get 'terms' => 'terms#index'
  get 'about' => 'about#index'
  get '/faq'  => 'common_questions#index'

  get 'stories' => 'pivotaltracker#show'
  
  resources :users

  resources :projects do
    resources :tasks
    resources :memberships
  end

  resources :tasks, only: [] do
    resources :comments, only: [:create]
  end
end

app/models/project.rb
class Project < ActiveRecord::Base


    validates :name, presence: true
    has_many :tasks, dependent: :destroy
    has_many :memberships, dependent: :destroy
    has_many :users, through: :memberships



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user
  before_action :project_member, only: [:edit, :show, :destroy, :update]
  before_action :project_owner, only: [:edit, :destroy, :update]


  def index
    if current_user.admin?
      @projects = Project.all
    else
      @projects = current_user.projects
    end

    if current_user.tracker_token
       tracker_api = TrackerAPI.new
       @tracker_projects = tracker_api.projects(current_user.tracker_token)
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
       @project.memberships.create(user_id: current_user.id, role: "Owner")
      flash[:success] = "Project was successfully created"
      redirect_to project_tasks_path(@project)
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
      if @project.update(project_params)
        flash[:success] = "Project was successfully updated!"
        redirect_to project_path(@project)
      else
        render :edit
      end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:success] = "Project was successfully deleted"
    redirect_to projects_path
  end


  private

  def project_params
    params.require(:project).permit(:name)
  end
end

app/views/projects/_form.html.erb
<%= form_for @project, html: {class: 'form-horizontal'} do |f| %>


<%= render partial: "shared/errors", locals: { object: @project } %>



  <div class= 'form-group'>
      <%= f.label :name, class: 'col-sm-2 control-label'%>
    <div class= 'col-sm-4'>
      <%= f.text_field :name, autofocus: true, class: 'form-control' %>
    </div>
  </div>




  <div class= 'form-group'>
    <div class= 'col-sm-offset-2 col-sm-10'>
      <%= f.submit "#{name_of_button} Project", class: 'btn btn-primary' %>
      <%= link_to "Cancel", projects_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<div class= 'container'>
      <h1>Edit Project</h1>
    <hr>

    <ol class='breadcrumb'>
      <li> <%= link_to 'Projects', projects_path %></li>
      <li> <%= link_to @project.name, project_path(@project) %></li>

      <li class="active">Edit</li>
    </ol>

</div>


  <%= render partial: "form", locals: { name_of_button: "Update"} %>

app/views/projects/index.html.erb
<div class= 'container'>
  <div class = 'page-header'>
    <%= link_to 'New Project', new_project_path, class: "btn btn-info pull-right" %>
    <h1>Projects</h1>
  </div>


<table class = "table">

      <thead>
        <tr>
          <th><strong> Name </strong></th>
          <th><strong>Task</strong></th>
        </tr>
      </thead>

  <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.name, project_path(project) %></td>
      <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
    </tr>
  <% end %>
</table>

  <% if current_user.tracker_token && @tracker_projects.class == Array %>
    <h1>Pivotal Tracker Projects</h1>

      <table class = "table">
          <thead>
            <tr>
              <th><strong> Name </strong></th>
            </tr>
          </thead>

        <% @tracker_projects.each do |tproject| %>
          <tr>
            <td> <%= link_to tproject[:name], stories_path(id: tproject[:id], project_name: tproject[:name]) %> </td>
          </tr>
        <% end %>
      </table>
  <% end %>


</div>

app/views/projects/new.html.erb
<div class= 'container'>
      <h1>New Project</h1>
    <hr>

    <ol class='breadcrumb'>
      <li> <%= link_to 'Projects', projects_path %></li>
      <li class="active">New Project</li>
    </ol>

</div>

  <%= render partial: "form", locals: { name_of_button: "Create"} %>

app/views/projects/show.html.erb
<div class = "container">
    <div class = "page-header">

        <div class= "pull-right">
          <% if current_user.is_project_owner(@project) %>
          <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-info" %>
          <% end %>
        </div>

        <h1><%= @project.name %></h1>

    </div>

      <ol class='breadcrumb'>
        <li><%= link_to 'Projects', projects_path %></li>
        <li class="active"><%= @project.name %></li>
      </ol>

  <%= link_to "#{pluralize(@project.tasks.count,"Task")}", project_tasks_path(@project) %>
  <br>
  <%= link_to "#{pluralize(@project.memberships.count,"Membership")}", project_memberships_path(@project) %>

<% if current_user.is_project_owner(@project)%>
    <div class="well">
      <head>Delete Project<head>
        <p><%= "Deleting this project will also delete #{pluralize(@project.memberships.count,"membership")}" + ', ' + "#{pluralize(@project.tasks.count,"task")} and associated comments" %></p>
        <p><%= link_to 'Destroy', project_path(@project), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" }%></p>
    </div>
<% end %>

</div>